### ISSUE TITLE
Unexpected Token Error

### ISSUE THREAD

**Issue by Kinnardian** [alexbbt/facebook-group-export#1]
I get an `Unexpected Token Error` when I run `$ facebook-group-export -a Token -g groupID`:

 ```
/usr/local/lib/node_modules/facebook-group-export/bin/index.js:113
const next_loop = function(paramaters, url, rows, page = 1) {
                                                       ^

SyntaxError: Unexpected token =
```

**Comment by alexbbt** [comment]
You are running a version of Node which does not support optional parameters. You will need to upgrade your version or node to >6.9 or wait for a later release of this package without that dependency.

**Comment by alexbbt** [comment]
The `token` in question here refers to a character, not the `Facebook Token`
